---
title: "Taxonomic Consistency Test"
---

```{r, include=FALSE}
# output directories
dir_allhits <- file.path(currentdir, "allhits")
if (!dir.exists(dir_allhits)) {
    dir.create(dir_allhits, recursive=T)
}

if (length(list.files(dir_allhits, recursive=T))!=0 & !params$redo) {
    log4r::error(fn_logger, "Error: output directory is not empty. Exited.")
    knitr::knit_exit()
}

# open metadata file
df_metadata <- data.table::fread(params$file_taxonomy_metadata)
if (!all(params$taxonomic_rank %in% colnames(df_metadata))) {
    log4r::error(fn_logger, "Error: one or more taxonomic ranks are not found in the metadata file. Exited.")
    knitr::knit_exit()
}

# extract list of trees
ls_trees <- list.files(params$dir_gene_tree, recursive=F, full.names=F)
if (length(ls_trees)<1) {
    log4r::error(fn_logger, "Error: list of gene trees is of length zero. Exited.")
    knitr::knit_exit()
}

# open list of tips
ls_tips_check <- c()
if (file.exists(params$file_list_tips) && params$file_list_tips!="") {
    ls_tips_check <- readLines(params$file_list_tips)

    if (length(ls_tips_check)<1) {
        log4r::error(fn_logger, "Error: list of tips is of length zero. Exited.")
        knitr::knit_exit()
    }
}

# output files
fn_prefix_output <- file.path(dir_allhits, params$prefix)
```

```{r taxonomic-consistency, include=FALSE}
# create doSNOW cluster
nwcl <- makeCluster(params$thread)
doSNOW::registerDoSNOW(nwcl)

# update log file
if (length(ls_tips_check)<1) {
    log4r::info(fn_logger, paste("Starting taxonomic consistency test on all samples across", length(ls_trees), "trees..."))
} else {
    log4r::info(fn_logger, paste("Starting taxonomic consistency test on", length(ls_tips_check), "samples across", length(ls_trees), "trees..."))
}

if (!params$keep_ties) {
    log4r::info(fn_logger, "Loci with tied majority will be filtered out!")
}

# iterate over gene trees
df_all_hits <- foreach(fn_tree = ls_trees, .combine='rbind', .export="f_extract_closest_group") %dopar% {
    require(ape)
    require(dplyr)

    # extract locus name
    locus <- tools::file_path_sans_ext(basename(fn_tree))

    # open treefile
    tre <- ape::read.tree(file.path(params$dir_gene_tree, fn_tree))
    if (length(ls_tips_check)<1) {
        ls_tips_check <- tre$tip.label
    }

    # create distance matrix
    dist_matrix <- ape::cophenetic.phylo(tre)

    # output data.frame
    df_hits_tips <- NULL

    # iterate over tips
    for (tips in ls_tips_check) {
        # check if sample exists
        if (!tips%in%tre$tip.label) {
            next
        }

        # extract distances from the tip
        dist_to_tips <- dist_matrix[tips, ]
        dist_to_tips <- dist_to_tips[names(dist_to_tips) != tips]

        # iterate over number of neighbours
        for (n in params$n_neighbour) {
            df_hits_temp <- f_extract_closest_group(dist_to_tips, n, params$taxonomic_rank, df_metadata, params$keep_ties) %>%
                                mutate(tips=tips, locus=locus, n_tips=length(tre$tip.label), n_neighbour=n) %>%
                                select(tips, locus, n_tips, n_neighbour, rank_level, weight, !!!syms(params$taxonomic_rank))

            df_hits_tips <- rbind(df_hits_tips, df_hits_temp)
        }
    }

    return(df_hits_tips)
}

stopCluster(nwcl)

# check if output data.frame is NULL
if (is.null(df_all_hits) || nrow(df_all_hits)==0) {
  log4r::error(fn_logger, "Error: no hits found. Exited.")
  knitr::knit_exit()
}

# extract list of tips
for (tip in unique(df_all_hits$tips)) {
    df_all_hits_tips <- df_all_hits %>% filter(tips==tip) %>% arrange(locus)
    data.table::fwrite(df_all_hits_tips, file=file.path(dir_allhits, paste0(tip, ".tsv")), sep="\t", quote=F)       
}
```

```{r best-taxonomy-hits, include=FALSE}
# iterate over number of neighbours
log4r::info(fn_logger, "Extracting the best hits for individual samples...")

for (n in params$n_neighbour) {
    # output data.frame
    df_best_hits <- NULL
    df_best_hits_weighted <- NULL
    df_entropy <- NULL

    # iterate over taxonomic ranks
    for (level in params$taxonomic_rank) {
        # group hits by tips
        df_hits_per_tips <- df_all_hits %>%
                                filter(n_neighbour==n & rank_level==level) %>%
                                group_by(tips) %>%
                                mutate(n_locus_total=n_distinct(locus)) %>%
                                group_by(tips, !!sym(level)) %>%
                                summarise(
                                    n_locus=n_distinct(locus),
                                    n_locus_weighted=sum(weight),
                                    n_locus_total=first(n_locus_total),
                                    prop_locus=round(n_locus/n_locus_total*100,3),
                                    prop_locus_weighted=round(n_locus_weighted/n_locus_total*100,3)) %>%
                                arrange(tips, desc(prop_locus_weighted))
        
        # save data.frame
        fn_hits_per_tips <- file.path(currentdir, paste0("prop_", level, "_", n, "neighbours.tsv"))
        data.table::fwrite(df_hits_per_tips, file=fn_hits_per_tips, sep="\t", quote=F)

        # calculate Shannon's entropy
        df_entropy_level <- df_hits_per_tips %>%
                                group_by(tips) %>%
                                mutate(prop_total=sum(prop_locus), prop_locus=prop_locus/prop_total,
                                       prop_total_weighted=sum(prop_locus_weighted), prop_locus_weighted=prop_locus_weighted/prop_total_weighted) %>%
                                group_by(tips) %>%
                                summarise("eff_{level}" := round(exp(-sum(prop_locus * log(prop_locus))),3),
                                          "eff_{level}_weighted" := round(exp(-sum(prop_locus_weighted * log(prop_locus_weighted))),3))

        # update the data.frame
        if (is.null(df_entropy)) {
            df_entropy <- df_entropy_level
        } else {
            df_entropy <- merge(df_entropy, df_entropy_level, by="tips", all=TRUE)
        }

        # extract data.frame
        df_best_hit_per_tips <- df_hits_per_tips %>% group_by(tips) %>% arrange(tips, desc(prop_locus)) %>% slice_max(prop_locus, n=1, with_ties=FALSE)
        df_best_hit_per_tips_weighted <- df_hits_per_tips %>% group_by(tips) %>% arrange(tips, desc(prop_locus_weighted)) %>% slice_max(prop_locus_weighted, n=1, with_ties=FALSE)

        # update the data.frame
        df_best_hit_per_tips <- df_best_hit_per_tips %>%
                                    rename("n_{level}" := n_locus,
                                           "n_{level}_weighted" := n_locus_weighted, 
                                           "prop_{level}" := prop_locus,
                                           "prop_{level}_weighted" := prop_locus_weighted)
        df_best_hit_per_tips_weighted <- df_best_hit_per_tips_weighted %>%
                                            rename("n_{level}" := n_locus,
                                                   "n_{level}_weighted" := n_locus_weighted, 
                                                   "prop_{level}" := prop_locus,
                                                   "prop_{level}_weighted" := prop_locus_weighted)

        if (is.null(df_best_hits) && is.null(df_best_hits_weighted)) {
            df_best_hits <- df_best_hit_per_tips
            df_best_hits_weighted <- df_best_hit_per_tips_weighted
        } else {
            df_best_hits <- merge(df_best_hits, df_best_hit_per_tips, by=c("tips", "n_locus_total"), all=TRUE)
            df_best_hits_weighted <- merge(df_best_hits_weighted, df_best_hit_per_tips_weighted, by=c("tips", "n_locus_total"), all=TRUE)
        }
    }

    # save data.frames
    fn_best_hits <- file.path(currentdir, paste0("besthits_", n, "neighbours.tsv"))
    fn_best_hits_weighted <- file.path(currentdir, paste0("besthits_weighted_", n, "neighbours.tsv"))
    data.table::fwrite(df_best_hits, file=fn_best_hits, sep="\t", quote=F)
    data.table::fwrite(df_best_hits_weighted, file=fn_best_hits_weighted, sep="\t", quote=F)

    # save data.frame
    fn_eff <- file.path(currentdir, paste0("eff_", n, "neighbours.tsv"))
    data.table::fwrite(df_entropy, file=fn_eff, sep="\t", quote=F)
}

log4r::info(fn_logger, "Finished!")
```

```{r match-taxonomy-hits, include=FALSE}
# iterate over number of neighbours
log4r::info(fn_logger, "Extracting matching hits for individual samples...")

# extract list of tips
ls_tips_check <- unique(df_all_hits$tips)

# create doSNOW cluster
nwcl <- makeCluster(params$thread)
doSNOW::registerDoSNOW(nwcl)

# iterate over number of neighbours
for (n in params$n_neighbour) {
    # iterate over samples
    df_matching_hits <- foreach(tip=ls_tips_check, .combine='rbind') %dopar% {
        require(dplyr)

        # extract metadata entry (if any)
        df_metadata_tip <- df_metadata[df_metadata$sample==tip,]
        if (nrow(df_metadata_tip)!=1) {
            return(NULL)
        }

        # output data.frame
        df_match_hit <- NULL

        # iterate over taxonomic ranks
        for (rank in params$taxonomic_rank) {
            # input files
            fn_hits_per_tips <- file.path(currentdir, paste0("prop_", rank, "_", n, "neighbours.tsv"))
            df_hits_per_tips <- data.table::fread(fn_hits_per_tips)
            
            # extract the taxon
            taxon_group <- df_metadata_tip %>% pull(!!sym(rank))
            df_hit_group <- df_hits_per_tips %>%
                                filter(tips==tip & !!sym(rank)==taxon_group)
            
            # set the proportion to be zero if group is not found
            if (nrow(df_hit_group)==0) {
                df_hit_group <- df_hits_per_tips %>%
                                    filter(tips==tip) %>%
                                    slice_head(n=1) %>%
                                    mutate(!!sym(rank):=taxon_group, n_locus=0, n_locus_weighted=0, prop_locus=0, prop_locus_weighted=0)
            }

            # update the data.frame
            df_hit_group <- df_hit_group %>%
                                rename("n_{rank}" := n_locus,
                                       "n_{rank}_weighted" := n_locus_weighted, 
                                       "prop_{rank}" := prop_locus,
                                       "prop_{rank}_weighted" := prop_locus_weighted)

            if (is.null(df_match_hit)) {
                df_match_hit <- df_hit_group
            } else {
                df_match_hit <- merge(df_match_hit, df_hit_group, by=c("tips", "n_locus_total"), all=TRUE)
            }
        }

        return(df_match_hit)
    }

    # save data.frame
    if (!is.null(df_matching_hits) && nrow(df_matching_hits)>0) {
        fn_match_hits <- file.path(currentdir, paste0("matchhits_", n, "neighbours.tsv"))
        data.table::fwrite(df_matching_hits, file=fn_match_hits, sep="\t", quote=F)
    }
}    

stopCluster(nwcl)

log4r::info(fn_logger, "Finished!")
```

```{r, results='asis', echo=FALSE}
# iterate over taxonomic ranks (source: Claude)
for (rank in params$taxonomic_rank) {
    # output data.frame
    df_level_wide <- NULL
    df_level_wide_weighted <- NULL

    # iterate over number of neighbours
    for (n in params$n_neighbour) {
        # open output files
        fn_best_hits <- file.path(currentdir, paste0("besthits_", n, "neighbours.tsv"))
        fn_best_hits_weighted <- file.path(currentdir, paste0("besthits_weighted_", n, "neighbours.tsv"))
        fn_eff <- file.path(currentdir, paste0("eff_", n, "neighbours.tsv"))

        df_best_hits <- data.table::fread(fn_best_hits)
        df_best_hits_weighted <- data.table::fread(fn_best_hits_weighted)
        df_eff <- data.table::fread(fn_eff)

        # extract the proportion and effective number of categories
        prop_rank <- paste0("prop_", rank)
        prop_rank_weighted <- paste0("prop_", rank, "_weighted")
        eff_rank <- paste0("eff_", rank)
        eff_rank_weighted <- paste0("eff_", rank, "_weighted")

        df_sub <- df_best_hits %>%
                    select(tips, !!sym(rank), !!sym(prop_rank)) %>%
                    left_join(df_eff %>% select(tips, !!sym(eff_rank)), by="tips") %>%
                    rename("taxon_n{n}" := !!sym(rank),
                           "prop_n{n}" := !!sym(prop_rank),
                           "eff_n{n}" := !!sym(eff_rank))

        df_sub_weighted <- df_best_hits_weighted %>%
                            select(tips, !!sym(rank), !!sym(prop_rank_weighted)) %>%
                            left_join(df_eff %>% select(tips, !!sym(eff_rank_weighted)), by="tips") %>%
                            rename("taxon_n{n}" := !!sym(rank),
                                   "prop_n{n}" := !!sym(prop_rank_weighted),
                                   "eff_n{n}" := !!sym(eff_rank_weighted))

        # update the output data.frame
        if (is.null(df_level_wide) && is.null(df_level_wide_weighted)) {
            df_level_wide <- df_sub
            df_level_wide_weighted <- df_sub_weighted
        } else {
            df_level_wide <- merge(df_level_wide, df_sub, by="tips", all=TRUE)
            df_level_wide_weighted <- merge(df_level_wide_weighted, df_sub_weighted, by="tips", all=TRUE)
        }
    }

    # enforce column order
    ordered_cols <- "tips"
    for (n in params$n_neighbour) {
        ordered_cols <- c(ordered_cols, paste0("taxon_n",n), paste0("prop_n",n), paste0("eff_n",n))
    }
    df_level_wide <- df_level_wide %>% select(all_of(ordered_cols))
    df_level_wide_weighted <- df_level_wide_weighted %>% select(all_of(ordered_cols))

    cat("\n\n## Taxonomic rank:", rank)
    cat("\n\n### Unweighted:", "\n\n")

    # create top header for the data.frame
    header_top <- c(" " = 1)
    for (n in params$n_neighbour) {
        header_top <- c(header_top, setNames(3, paste0("n_neighbour==", n)))
    }

    # update the column labels to be consistent
    col_labels <- c("Tips", rep(c("Taxon", "Prop (%)", "Eff"), times=length(params$n_neighbour)))

    # create output data.frame
    html_tabel <- knitr::kable(df_level_wide, col.names=col_labels, format="html", escape=FALSE) %>%
                    kable_styling(bootstrap_options=c("striped", "hover", "condensed"), full_width=TRUE) %>%
                    add_header_above(header_top) %>%
                    scroll_box(height="400px", width="100%")

    print(html_tabel)

    cat("\n\n### Weighted:", "\n\n")

    # create output data.frame
    html_tabel <- knitr::kable(df_level_wide_weighted, col.names=col_labels, format="html", escape=FALSE) %>%
                    kable_styling(bootstrap_options=c("striped", "hover", "condensed"), full_width=TRUE) %>%
                    add_header_above(header_top) %>%
                    scroll_box(height="400px", width="100%")

    print(html_tabel)
    cat("\n\n")
}
```